### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [JuliaSparse/HarwellRutherfordBoeing.jl#14]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by dpo** [comment]
This package indeed supports 1.0: https://travis-ci.org/JuliaSparse/HarwellRutherfordBoeing.jl. Please don't remove it from the registry. I'm happy to transition to the Project.toml format.

**Comment by KristofferC** [comment]
Yeah, with supports 1.0 I mean:

```
(v1.2) pkg> add HarwellRutherfordBoeing.jl
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HarwellRutherfordBoeing [ce388394]:
 HarwellRutherfordBoeing [ce388394] log:
 ├─possible versions are: 0.0.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Updating to Project.toml and tagging a new version supporting 1.0 is enough for it to be kept in the registry.
