### ISSUE TITLE
Mind tagging a version?

### ISSUE THREAD

**Issue by sbromberger** [JuliaSparse/HarwellRutherfordBoeing.jl#4]
I'd like to use this in LightGraphs.Datasets. Would you please tag an initial version for `Pkg.add`?

**Comment by dpo** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4116

**Comment by sbromberger** [comment]
Thank you - sorry it appears to have been such a pain!

**Comment by dpo** [comment]
`Pkg.add("HarwellRutherfordBoeing")` should work now, and it should be possible to add it to your `REQUIRE` file.
